name: Publish Release
on:
  push:
    branches: [main]
jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - run: hub release create -m "ArgoCD-${{ github.sha }}" -m "version:${{ github.sha }}" "$(date +%Y%m%d%H%M%S)"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
