name: Publish Release
on:
  push:
    branches: [main]
jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: |
        sha_short=$(git rev-parse --short HEAD)
        hub release create -m "ArgoCD-$sha_short" \
          -m "This is an ArgoCD Release!
          If you need to roll back to this version, you can copy the sha version and execute the rollout action.
          sha-version: '${{ github.sha }}'" \
          "$sha_short"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
